### ISSUE TITLE
Explanations would help a lot

### ISSUE THREAD

**Issue by PatrickMassot** [The-Compiler/homebrew-qt5-webkit#2]
It seems this repository is about fighting the nightmare of Qt dropping Webkit. Unfortunately I find it very difficult to use without explanation.

I put a lot of efforts into some PyQt project. The reason why I chose Qt in the first place was the promise that my script could run on Linux/Mac/Windows. But now everything is broken because it seems very hard to install PyQt5 with Webkit on MacOS and at least as hard to install PyQt5 with QtWebEngine on Linux (Debian).

I don't care about security holes in Webkit, my app only loads html it generates itself. I don't mind learning QtWebEngine. I only need help to use either of these strategies on MacOS and Linux simultaneously.

Note I'm not a Mac user, I borrowed a MacBook and spent the last two evening trying to use homebrew with no success. And I would very much prefer if there is a way out of this nightmare without getting an Apple id or whatever Apple wants from me to let me install xcode or whatever. I think I managed to install either your formula or an old version of Qt5 but never managed to get PyQt to use it, (tried checking out old versions of the formula, tried [this gist](https://gist.github.com/Linuus/6f7be8dfa599aa0c96b2)... no luck).

**Comment by The-Compiler** [comment]
I've had things working for [my own PyQt project](https://www.qutebrowser.org/) with this repo for a while, but in the meantime I gave up because the maintaince burden of creating a Homebrew bottle (binary package) on every Qt update was too high (and for some reason Homebrew refuses to install older bottles...) - so consider this repository abandoned, I'm afraid.

I feel your pain, and I don't have an easy answer for you, at least until Debian manages to package QtWebEngine. However, I can also see why Qt wanted to drop QtWebKit.

If you only need to show simple HTML without much else, I can imagine two solutions:
- Use [QTextBrowser](http://doc.qt.io/qt-5/qtextbrowser.html) which can also show simple HTML.
- Try to use QtWebEngine, and if that isn't available, fall back to using QtWebKit

I'm going to close this as I don't plan to act on it in any way (sorry!), but feel free to continue the discussion.

**Comment by PatrickMassot** [comment]
Thank you very much for your answer. I'm afraid QTextBrower is not enough for my project. It seems the only way forward is to manage to install QtWebEngine on my Debian: many painful nights ahead...

**Comment by The-Compiler** [comment]
@PatrickMassot Just a small heads-up, seems like the official Homebrew package gained a `--with-webkit` option again: https://github.com/Homebrew/homebrew-core/pull/4107

**Comment by PatrickMassot** [comment]
Thank you very much for the information. In the mean time I managed to install QtWebEngine on my Debian and adjust my program but it's very good to hear that QtWebKit is not dead. It's rather annoying to use Javascript for everything with QtWebEngine where we have a pythonic interface in QtWebKit.
